name: Metrics
on:
  # Se ejecuta automáticamente cada 24 horas
  schedule: [{cron: "0 0 * * *"}]
  # Permite ejecución manual desde la pestaña Actions
  workflow_dispatch:
  # Se ejecuta al hacer push a la rama principal
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Genera la cabecera general (Estadísticas)
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: eduardiazcode
          filename: header.svg
          base: header, activity, community, repositories, metadata
          config_timezone: America/Lima

      # Genera el desglose de lenguajes de programación
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: eduardiazcode
          filename: languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          config_timezone: America/Lima
