name: Metrics
on:
  # Se ejecuta automÃ¡ticamente cada 24 horas
  schedule: [{cron: "0 0 * * *"}]
  # Permite ejecutarlo manualmente desde la pestaÃ±a Actions (para pruebas)
  workflow_dispatch:
  # Se ejecuta cada vez que haces push a la rama master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Tu token secreto
          token: ${{ secrets.METRICS_TOKEN }}

          # Opciones bÃ¡sicas
          user: eduardiazcode
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Lima

          # ðŸ§© Plugin: IsometrÃ­a (El calendario 3D cool)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # ðŸ§© Plugin: Lenguajes (Detallado)
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8

          # ðŸ§© Plugin: Logros (Trofeos)
          plugin_achievements: no
          plugin_achievements_display: compact
